### ISSUE TITLE
Failover when remote multicluster service doesn't have endpoints

### ISSUE THREAD

**Issue by oliviermichaelis** [linkerd/linkerd-failover#175]
The `README` states:
https://github.com/linkerd/linkerd-failover/blob/345b7c14c6a2af5746262654bf57a497b9b89313/README.md?plain=1#L103-L106

Let's assume we have `example-mirror`, a service mirrored from another remote cluster which we're using as our primary service in a `TrafficSplit`

```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: example
  annotations:
    failover.linkerd.io/primary-service: example-mirror
  labels:
    failover.linkerd.io/controlled-by: linkerd-failover
spec:
  service: example
  backends:
  - service: example-mirror
    weight: 1
  - service: example-backup
    weight: 0
``` 

The `Endpoint` for `example-mirror` will have an address pointing to the remote cluster. If we remove all Pods targeted from the `example-mirror` service in the source cluster, the `Endpoint` will still have the address pointing to the remote cluster. The failover will only happen once we don't export the source service anymore. Thus, the failover criteria is different for cluster-local services than for exported (multicluster) services.

This might come across as nitpicking, but I'm genuinely interested how that problem could be solved :)
